## 应用名称
#spring.application.name=customer-ui
#
## 应用服务 WEB 访问端口
#server.port=8080
server:
  port: 9002
spring:
  application:
    name: customer-ui
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      isolation:
        thread:
          timeoutInMilliseconds: 1000
