## 应用名称
#spring.application.name=goods-ui
#
## 应用服务 WEB 访问端口
#server.port=8080
server:
  port: 8002
spring:
  application:
    name: goods-ui
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka

